- name: Merge SVG Components
  uses: ./path-to-your-action-directory
  with:
    layout: ${{ steps.read_layout.outputs.layout }}
    assets: "images/*.svg,images/*.png"
    token: ${{ secrets.GITHUB_TOKEN }}
