name: Merge SVG Profile Components

on:
  push:
    branches:
      - main
    # Run on any push to main, except when only merged.svg is updated
    paths-ignore:
      - 'public/merged.svg'
  workflow_dispatch:

jobs:
  merge-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allow pushing back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Merge SVG Components
        uses: ./           # your local Action
        with:
          layout: |
            [ … your layout JSON … ]
          assets: "images/*.svg,images/*.png"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy merged.svg to public folder
        run: |
          mkdir -p public
          cp merged.svg public/merged.svg

      - name: Commit and push updated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/merged.svg
          git commit -m "ci: update merged.svg for Vercel hosting" || echo "No changes to commit"
          git push
